exclude: (^notebooks/)
repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff
        language: system
        types: [ python ]
      - id: black
        name: black
        entry: black
        language: system
        types: [ python ]
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [ python ]
        exclude: (^docs/)
      - id: trailing-whitespace
        name: trailing-whitespace
        entry: trailing-whitespacepfixer
        language: system
        types: [ file, python ]
        exclude: (^docs/)
      - id: end-of-file-fixer
        name: end-of-file-fixer
        entry: end-of-file-fixer
        language: system
        types: [ file, python ]
        exclude: (^docs/)