[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"


[project]
name = "{{cookiecutter.project_slug}}"
version = "0.1.0"
description = "{{cookiecutter.project_short_description}}"
readme = "README.md"
license = { text ="MIT License" }
requires-python = ">={{cookiecutter.python_requires}}"

authors = [
    { name="{{cookiecutter.project_author}}", email="{{cookiecutter.author_email}}"}
]

dependencies = [
]


[project.optional-dependencies]
docs = [
    "sphinx",
    "sphinx-rtd-theme",
    "myst-parser",
    "tomli"
]

tests = [
    "coverage",
    "pytest",
    "pytest-cov",
    "toml",
    "pre-commit-hooks"
]

qa = [
    "pre-commit",
    "black",
    "flake8",
    "flake8-docstrings",
    "mypy",
    "nox",
    "check-manifest",
    "isort",
    "pylint"
]

build = [
    "twine",
    "wheel",
]

dev = [
    "{{cookiecutter.project_slug}}[docs]",
    "{{cookiecutter.project_slug}}[tests]",
    "{{cookiecutter.project_slug}}[qa]",
    "{{cookiecutter.project_slug}}[build]",
]


[project.urls]
"Sourcecode" = "https://github.com/chris-santiago/{{cookiecutter.project_slug}}"
"Documentation" = "https://chris-santiago.github.io/{{cookiecutter.project_slug}}/"


[tool.setuptools]
include-package-data = true
zip-safe = false


[tool.setuptools.packages.find]
where = ["."]
exclude = ["tests/*"]


[tool.check-manifest]
ignore = [
    "docs",
    "docs/**",
    "notebooks",
    "notebooks/**",
    ".pre-commit-config.yaml",
    ".gitignore",
    ".pylintrc",
    "Makefile",
    "noxfile.py",
]


[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
line_length = 100


[tool.mypy]
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true


[tool.pylint.master]
fail-under = 9.0
ignore-patterns = "test"
disable = [
    # Disable these for scikit-learn style code
    "invalid-name",
    "attribute-defined-outside-init",
]


[tool.pylint.format]
max-line-length = 100
max-module-lines = 1000


[tool.pylint.similarities]
min-similarity-lines = 4
ignore-comments = "yes"
ignore-docstrings = "yes"


[tool.pytest.ini_options]
testpaths = ["tests/"]
addopts = "--cov={{cookiecutter.project_slug}} --cov-report=html --verbose"
