version: "3"

# You can also ask Task to include .env like files by using the dotenv: setting:
{% raw %}dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']{% endraw %}

# If `--` is given in the CLI, all following parameters are added to a special .CLI_ARGS variable.
# This is useful to forward arguments to another command.

tasks:

  check-config:
    desc: Check Hydra configuration
    cmds:
      - python {{cookiecutter.project_slug}}/train.py --cfg all --resolve {% raw %}{{.CLI_ARGS}}{% endraw %}

  wandb:
    desc: Login to Weights & Biases
    cmds:
      - wandb login $WANDB_KEY

  train:
    desc: Train a model
    cmds:
      - python {{cookiecutter.project_slug}}/train.py {% raw %}{{.CLI_ARGS}}{% endraw %}