version: "3"

# You can also ask Task to include .env like files by using the dotenv: setting:
dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

# If `--` is given in the CLI, all following parameters are added to a special .CLI_ARGS variable.
# This is useful to forward arguments to another command.

tasks:

  default:
    cmds:
      - echo "Hello, visit https://taskfile.dev/usage/ for usage docs."
